[package]
name = "rust-cef"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rust_cef"

[[bin]]
name = "cef_mac_helper_process"

[dependencies]
cef-sys = { path = "../cef-sys" }
