[package]
name = "cef_mac_helper"
version.workspace = true
edition.workspace = true

[dependencies]
rust_cef ={ workspace = true, features = ["bundled"] }
cef_wrapper.workspace = true

[features]
default = []
