[package]
name = "rhythmium"
description = "A Rhythm Game Client"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
bytemuck.workspace = true
env_logger.workspace = true
image = { workspace = true, features = ["jpeg", "png"] }
log.workspace = true
rand = "0.8.5"
serde.workspace = true
slotmap = "1.0.7"
taffy = { version = "0.3.18", features = ["serde"] }
tokio.workspace = true
wgpu.workspace = true
winit.workspace = true
cef_wrapper.workspace = true