/// The raw CEF C API bindings, generated by bindgen.
pub mod cef_capi_sys {
    #![allow(non_upper_case_globals)]
    #![allow(non_camel_case_types)]
    #![allow(non_snake_case)]
    #![allow(dead_code)]
    #![allow(clippy::type_complexity)]

    include!(concat!(env!("OUT_DIR"), "/bindings_c.rs"));
}

/// The manual bindings for the library loading functions for macos.
#[cfg(target_os = "macos")]
pub mod cef_wrapper_sys {
    unsafe extern "C" {
        pub fn cef_load_library(path: *const std::ffi::c_char) -> std::ffi::c_int;
        pub fn cef_unload_library() -> std::ffi::c_int;
    }
}
