[package]
name = "cef_wrapper"
description = "A Rhythm Game Client"
version.workspace = true
edition.workspace = true

[lib]
doctest = false

[build-dependencies]
cmake = "0.1"
bindgen = "0.69"
regex = "1.10.3"
